### PR TITLE
minor fix in I.5.12

### PR DESCRIPTION
**Pull request by jzxia**
The solution to exercise I.5.12 starts by defining the "concrete" version of fibered product in an arbitrary category C, which is inaccurate. This should be confined to the category of sets.

### CODE REVIEW

**Review by hooyuser — CHANGES_REQUESTED** [review]
It seems cannot be merged automatically. I believe renaming it `Solution_to_Algebra_Chapter_0.tex` will solve this problem.

**Comment by jzxia** [comment]
Sorry for the trouble! I forgot to fetch upstream before making changes. I'm trying to resolve this issue.

**Comment by jzxia** [comment]
I did a merge on my forked branch, incorporating all your recent updates. This pull request is now ready to be merged automatically.

**Comment by hooyuser** [comment]
Thanks! It works fine now.

**Pull request merged**
